### ISSUE TITLE
Build error on Ubuntu

### ISSUE THREAD

**Issue by codygman** [mchav/GeoQuiz-Frege#2]
```
4:48:31 PM Gradle sync failed: /home/cody/sources/GeoQuiz-Frege/app/build/intermediates/exploded-aar/com.android.support
Error:(86, 1) A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > /home/cody/sources/GeoQuiz-Frege/app/build/intermediates/exploded-aar/com.android.support
```

**Comment by mchav** [comment]
I think it's because the build file hasn't been made at the time at which you're trying to compile. 

Changing the functional call for `compileFrege()` to `compileDebugJavaWithJavac.doFirst { compileFrege() }` should work.

**Comment by mchav** [comment]
@codygman made some changes to the gradle build. Should work now.

**Comment by codygman** [comment]
@mchav It built for me!

**Comment by mchav** [comment]
@codygman great. Let me know if you find any other bugs - I'll be working on this for the weekend.
